
server:
  port: 8080

# Luwian Configuration
luwian:
  logging:
    json: true
    http:
      body: false
    tenancy-header: X-Tenant
  error:
    include-stacktrace: on-trace
  metrics:
    enabled: true
    service: quickstart-spring
    environment: development
    version: 1.0.0
    aop-timed: false

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
